 create table members ( 
 		       id int(5) not null auto_increment unique,	
 		       mid varchar(50) not null unique,
                       name varchar(50) not null,
                       plce varchar(50) not null,
                       reln_ms int(2) not null,
                       fbid varchar(120), enfb bool,
                       twid varchar(120), entw bool,
                       lnin varchar(120), enln bool,
                       ghub varchar(120), emgh bool,
                       picurl varchar(120), enpic bool,
                       mob int(10), enmob bool,
                       bio varchar(300),
                       regdate date,
                       validity date,
		       address varchar(200), enad bool,
		       college varchar(100),
		       collegelocation varchar(50),
		       email varchar(120) not null,
		       blog varchar(120),
                       app_stat bool);
                       
